### ISSUE TITLE
problem in vctk preprocessing.

### ISSUE THREAD

**Issue by pegasus189674** [r9y9/deepvoice3_pytorch#133]
Hello.
I have encountered a problem while I run vctk_preprocess.py.
I can not understand why the file is not loaded.
this is a log.
How can I solve this problem? Or may I ignore this problem?

> ... Traceback (most recent call last):
  File "./extract_feats.py", line 1439, in <module>
    keep_silences, full_features)
  File "./extract_feats.py", line 528, in extract_intermediate_features
    with open("do_ehmm", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'do_ehmm'
cp ./latest_features/merlin/misc/scripts/alignment/phone_align/full-context-labels/mono/*.lab ../../data/lab/p225
cp: './latest_features/merlin/misc/scripts/alignment/phone_align/full-context-labels/mono/*.lab' を stat できません: そのようなファイルやディレクトリはありません
rm -rf ./latest_features
  1%|▍                                        | 1/108 [00:42<1:15:00, 42.06s/it]../../data/VCTK-Corpus/wav48/p226 ../../data/VCTK-Corpus/txt/p226
python ./extract_feats.py -w ../../data/VCTK-Corpus/wav48/p226 -t ../../data/VCTK-Corpus/txt/p226
^CTraceback (most recent call last):
  File "prepare_vctk_labels.py", line 43, in ...<module>

And that's the directory where it is running.
> src/ehmm/bin
├── ConvertFeatsFileToBinaryFormat
├── FeatureExtraction
├── Makefile
├── ScaleBinaryFeats
├── check_lab.pl
├── comp_dcep.pl
├── do_ehmm
├── edec
├── ehmm
├── phfromutt.pl
├── phseq.scm
├── rem_ssil.pl
├── rm_nan_utts
├── scale_feat.pl
├── seqproc.pl
├── sl2nm.pl
└── sym2nm.pl

**Comment by pegasus189674** [comment]
Thank you very much. I had overlooked it.
There was an error when executing extruct_feats.py , so I will fix it.
