### ISSUE TITLE
ValueError in preprocess.py?

### ISSUE THREAD

**Issue by pegasus189674** [r9y9/deepvoice3_pytorch#135]
An error occured in preprocess.py but it has not stopped.
Should I do something? Or may I ignore it?
This is a log.

> concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/xxx/yyy/deepvoice3_pytorch/vctk.py", line 66, in _process_utterance
    wav, _ = librosa.effects.trim(wav, top_db=25)
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/librosa/effects.py", line 472, in trim
    top_db=top_db)
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/librosa/effects.py", line 417, in _signal_to_frame_nonsilent
    hop_length=hop_length)**2
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/librosa/feature/spectral.py", line 590, in rmse
    y = np.pad(y, int(frame_length // 2), mode=pad_mode)
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1420, in pad
    " in axis {} of `array`".format(axis))
ValueError: There aren't any elements to reflect in axis 0 of `array`
"""

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "preprocess.py", line 59, in <module>
    preprocess(mod, in_dir, out_dir, num_workers)
  File "preprocess.py", line 23, in preprocess
    metadata = mod.build_from_path(in_dir, out_dir, num_workers, tqdm=tqdm)
  File "/home/xxx/yyy/deepvoice3_pytorch/vctk.py", line 29, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "/home/xxx/yyy/deepvoice3_pytorch/vctk.py", line 29, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/xxx/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: There aren't any elements to reflect in axis 0 of `array`

**Comment by pegasus189674** [comment]
Perhaps my lab file is wrong.
Can anyone show me the lab file of VCTK?
This is my p225_018.lab.

          0    1500000 pau
   1500000    7500000 pau
   7500000   16250000 pau
  16250000   18350000 pau
  18350000   18500000 eh
  18500000   19800000 r
  19800000   19950000 ax
  19950000   20250001 s
  20250001   20400000 t
  20400000   20550001 aa
  20550001   20699999 t
  20699999   20850000 ax
  20850000   20999999 l
  20999999   21150000 th
  21150000   26150000 ao
  26150000   26300001 t
  26300001   26450000 dh
  26450000   26600001 ae
  26600001   26750000 t
  26750000   26900001 dh
  26900001   28299999 ax
  28299999   37650001 r
  37650001   37800000 ey
  37800000   37950001 n
  37950001   38099999 b
  38099999   38250000 ow
  38250000   38399999 w
  38399999   38550000 aa
  38550000   38800001 z
  38800001   38950000 k
  38950000   39100001 aa
  39100001   39250000 z
  39250000   39400001 d
  39400001   39900000 pau
  39900000   40050001 b
  40050001   40200000 ay
  40200000   42500000 r
  42500000   42649999 ax
  42649999   43449998 f
  43449998   43600001 l
  43600001   44699998 eh
  44699998   44850001 k
  44850001   45850000 sh
  45850000   45999999 ax
  45999999   46550002 n
         0          0 ah

**Comment by pegasus189674** [comment]
Preprocess.py now works by deleting files with phoneme errors.
I do not know whether this is correct, but I am training with this.
