### ISSUE TITLE
Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by kenyeung128** [r9y9/deepvoice3_pytorch#15]
Hi,

Is GPU a must requirement on the machine? I tried tp run the synthesis.py on the pre-trained model, but got the following error.

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by r9y9** [comment]
Yes, GPU is required for synthesis. I'm afraid I haven't got a chance to fix it for CPU.

Ref: https://github.com/r9y9/deepvoice3_pytorch/issues/1#issuecomment-352749070

**Comment by kenyeung128** [comment]
ok, now i run on gpu, but got this error, do u have any idea?

THCudaCheck FAIL file=/pytorch/torch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
Traceback (most recent call last):
  File "synthesis.py", line 124, in <module>
    checkpoint = torch.load(checkpoint_path)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 409, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 380, in persistent_load
    data_type(size), location)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 86, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 68, in _cuda_deserialize
    return obj.cuda(device)
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 61, in _cuda
    with torch.cuda.device(device):
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 186, in __enter__
    _lazy_init()
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 121, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/torch/lib/THC/THCGeneral.c:70

**Comment by r9y9** [comment]
Looks like a GPU driver problem. Maybe reboot your PC? Please check if

```
python -c "import torch; print(torch.cuda.is_available())"
```

returns True.

**Comment by kenyeung128** [comment]
works now, thanks
