### ISSUE TITLE
Multi-speaker DeepVoice3 failed to load on commit 0421749

### ISSUE THREAD

**Issue by mrgloom** [r9y9/deepvoice3_pytorch#151]
On commit `HEAD detached at 0421749` with model `MD5 (20171222_deepvoice3_vctk108_checkpoint_step000300000.pth) = 3344ea1a84c79ea3591329a0f88591d4`
running like 
`python synthesis.py 20171222_deepvoice3_vctk108_checkpoint_step000300000.pth sentences.txt temp`

Error:
```
Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': '',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': '20171222_deepvoice3_vctk108_checkpoint_step000300000.pth',
 '<dst_dir>': 'temp',
 '<text_list_file>': 'sentences.txt'}
Traceback (most recent call last):
  File "synthesis.py", line 126, in <module>
    model.load_state_dict(checkpoint["state_dict"])
  File "/Users/my_user/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/my_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiSpeakerTTSModel:
	Missing key(s) in state_dict: "seq2seq.decoder.preattention.3.conv.bias", "seq2seq.decoder.preattention.3.conv.weight_g", "seq2seq.decoder.preattention.3.conv.weight_v", "seq2seq.decoder.attention.4.query_projection.bias", "seq2seq.decoder.attention.4.query_projection.weight_g", "seq2seq.decoder.attention.4.query_projection.weight_v", "seq2seq.decoder.attention.4.out_projection.bias", "seq2seq.decoder.attention.4.out_projection.weight_g", "seq2seq.decoder.attention.4.out_projection.weight_v". 
	Unexpected key(s) in state_dict: "embed_speakers.weight", "seq2seq.encoder.speaker_fc1.bias", "seq2seq.encoder.speaker_fc1.weight_g", "seq2seq.encoder.speaker_fc1.weight_v", "seq2seq.encoder.speaker_fc2.bias", "seq2seq.encoder.speaker_fc2.weight_g", "seq2seq.encoder.speaker_fc2.weight_v", "seq2seq.encoder.convolutions.2.speaker_proj.bias", "seq2seq.encoder.convolutions.2.speaker_proj.weight_g", "seq2seq.encoder.convolutions.2.speaker_proj.weight_v", "seq2seq.encoder.convolutions.3.speaker_proj.bias", "seq2seq.encoder.convolutions.3.speaker_proj.weight_g", "seq2seq.encoder.convolutions.3.speaker_proj.weight_v", "seq2seq.encoder.convolutions.4.speaker_proj.bias", "seq2seq.encoder.convolutions.4.speaker_proj.weight_g", "seq2seq.encoder.convolutions.4.speaker_proj.weight_v", "seq2seq.encoder.convolutions.5.speaker_proj.bias", "seq2seq.encoder.convolutions.5.speaker_proj.weight_g", "seq2seq.encoder.convolutions.5.speaker_proj.weight_v", "seq2seq.encoder.convolutions.6.speaker_proj.bias", "seq2seq.encoder.convolutions.6.speaker_proj.weight_g", "seq2seq.encoder.convolutions.6.speaker_proj.weight_v", "seq2seq.encoder.convolutions.7.speaker_proj.bias", "seq2seq.encoder.convolutions.7.speaker_proj.weight_g", "seq2seq.encoder.convolutions.7.speaker_proj.weight_v", "seq2seq.encoder.convolutions.8.speaker_proj.bias", "seq2seq.encoder.convolutions.8.speaker_proj.weight_g", "seq2seq.encoder.convolutions.8.speaker_proj.weight_v", "seq2seq.encoder.convolutions.9.speaker_proj.bias", "seq2seq.encoder.convolutions.9.speaker_proj.weight_g", "seq2seq.encoder.convolutions.9.speaker_proj.weight_v", "seq2seq.encoder.convolutions.10.speaker_proj.bias", "seq2seq.encoder.convolutions.10.speaker_proj.weight_g", "seq2seq.encoder.convolutions.10.speaker_proj.weight_v", "seq2seq.encoder.convolutions.11.speaker_proj.bias", "seq2seq.encoder.convolutions.11.speaker_proj.weight_g", "seq2seq.encoder.convolutions.11.speaker_proj.weight_v", "seq2seq.decoder.speaker_proj1.bias", "seq2seq.decoder.speaker_proj1.weight_g", "seq2seq.decoder.speaker_proj1.weight_v", "seq2seq.decoder.speaker_proj2.bias", "seq2seq.decoder.speaker_proj2.weight_g", "seq2seq.decoder.speaker_proj2.weight_v", "seq2seq.decoder.preattention.2.speaker_proj.bias", "seq2seq.decoder.preattention.2.speaker_proj.weight_g", "seq2seq.decoder.preattention.2.speaker_proj.weight_v", "seq2seq.decoder.convolutions.0.speaker_proj.bias", "seq2seq.decoder.convolutions.0.speaker_proj.weight_g", "seq2seq.decoder.convolutions.0.speaker_proj.weight_v", "seq2seq.decoder.convolutions.1.speaker_proj.bias", "seq2seq.decoder.convolutions.1.speaker_proj.weight_g", "seq2seq.decoder.convolutions.1.speaker_proj.weight_v", "seq2seq.decoder.convolutions.2.speaker_proj.bias", "seq2seq.decoder.convolutions.2.speaker_proj.weight_g", "seq2seq.decoder.convolutions.2.speaker_proj.weight_v", "seq2seq.decoder.convolutions.3.speaker_proj.bias", "seq2seq.decoder.convolutions.3.speaker_proj.weight_g", "seq2seq.decoder.convolutions.3.speaker_proj.weight_v", "seq2seq.decoder.convolutions.4.speaker_proj.bias", "seq2seq.decoder.convolutions.4.speaker_proj.weight_g", "seq2seq.decoder.convolutions.4.speaker_proj.weight_v", "seq2seq.decoder.attention.0.key_projection.bias", "seq2seq.decoder.attention.0.key_projection.weight_g", "seq2seq.decoder.attention.0.key_projection.weight_v", "seq2seq.decoder.attention.0.value_projection.bias", "seq2seq.decoder.attention.0.value_projection.weight_g", "seq2seq.decoder.attention.0.value_projection.weight_v", "postnet.convolutions.2.speaker_proj.bias", "postnet.convolutions.2.speaker_proj.weight_g", "postnet.convolutions.2.speaker_proj.weight_v", "postnet.convolutions.3.speaker_proj.bias", "postnet.convolutions.3.speaker_proj.weight_g", "postnet.convolutions.3.speaker_proj.weight_v", "postnet.convolutions.5.speaker_proj.bias", "postnet.convolutions.5.speaker_proj.weight_g", "postnet.convolutions.5.speaker_proj.weight_v", "postnet.convolutions.6.speaker_proj.bias", "postnet.convolutions.6.speaker_proj.weight_g", "postnet.convolutions.6.speaker_proj.weight_v", "postnet.convolutions.7.speaker_proj.bias", "postnet.convolutions.7.speaker_proj.weight_g", "postnet.convolutions.7.speaker_proj.weight_v", "postnet.convolutions.8.speaker_proj.bias", "postnet.convolutions.8.speaker_proj.weight_g", "postnet.convolutions.8.speaker_proj.weight_v", "postnet.convolutions.11.speaker_proj.bias", "postnet.convolutions.11.speaker_proj.weight_g", "postnet.convolutions.11.speaker_proj.weight_v", "postnet.convolutions.12.speaker_proj.bias", "postnet.convolutions.12.speaker_proj.weight_g", "postnet.convolutions.12.speaker_proj.weight_v". 
	size mismatch for seq2seq.encoder.embed_tokens.weight: copying a param with shape torch.Size([149, 256]) from checkpoint, the shape in current model is torch.Size([149, 128]).
	size mismatch for seq2seq.encoder.convolutions.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for seq2seq.encoder.convolutions.0.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.0.weight_v: copying a param with shape torch.Size([512, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1]).
	size mismatch for seq2seq.encoder.convolutions.2.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.2.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.2.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.3.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.3.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.3.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.4.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.4.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.4.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.5.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.5.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.5.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.6.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.6.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.6.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.7.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.7.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.7.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.8.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.8.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.8.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.9.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.9.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.9.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.10.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.10.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.10.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.11.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for seq2seq.encoder.convolutions.11.conv.weight_g: copying a param with shape torch.Size([1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.11.conv.weight_v: copying a param with shape torch.Size([1024, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3]).
	size mismatch for seq2seq.encoder.convolutions.12.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for seq2seq.encoder.convolutions.12.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.12.weight_v: copying a param with shape torch.Size([256, 512, 1]) from checkpoint, the shape in current model is torch.Size([128, 256, 1]).
	size mismatch for seq2seq.decoder.embed_query_positions.weight: copying a param with shape torch.Size([1024, 256]) from checkpoint, the shape in current model is torch.Size([512, 256]).
	size mismatch for seq2seq.decoder.embed_keys_positions.weight: copying a param with shape torch.Size([1024, 256]) from checkpoint, the shape in current model is torch.Size([512, 128]).
	size mismatch for seq2seq.decoder.attention.0.query_projection.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for seq2seq.decoder.attention.0.query_projection.weight_g: copying a param with shape torch.Size([256, 1]) from checkpoint, the shape in current model is torch.Size([128, 1]).
	size mismatch for seq2seq.decoder.attention.0.query_projection.weight_v: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
	size mismatch for seq2seq.decoder.attention.0.out_projection.weight_v: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 128]).

```

**Comment by mrgloom** [comment]
Following this:
https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/DeepVoice3_multi_speaker_TTS_en_demo.ipynb#scrollTo=Pqu6dICruu56

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-a62779839443> in <module>
      4 for speaker_id in range(N):
      5     print(speaker_id)
----> 6     tts(model, text, speaker_id=speaker_id, figures=False)

<ipython-input-5-c99d2a02082e> in tts(model, text, p, speaker_id, fast, figures)
      1 def tts(model, text, p=0, speaker_id=0, fast=True, figures=True):
      2     from synthesis import tts as _tts
----> 3     waveform, alignment, spectrogram, mel = _tts(model, text, p, speaker_id, fast)
      4     if figures:
      5         visualize(alignment, spectrogram)

~/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/synthesis.py in tts(model, text, p, speaker_id, fast)
     65     # Greedy decoding
     66     mel_outputs, linear_outputs, alignments, done = model(
---> 67         sequence, text_positions=text_positions, speaker_ids=speaker_ids)
     68 
     69     linear_output = linear_outputs[0].cpu().data.numpy()

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/deepvoice3_pytorch/__init__.py in forward(self, text_sequences, mel_targets, speaker_ids, text_positions, frame_positions, input_lengths)
     77         mel_outputs, alignments, done, decoder_states = self.seq2seq(
     78             text_sequences, mel_targets, speaker_embed,
---> 79             text_positions, frame_positions, input_lengths)
     80 
     81         # Reshape

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/deepvoice3_pytorch/__init__.py in forward(self, text_sequences, mel_targets, speaker_embed, text_positions, frame_positions, input_lengths)
    122             encoder_outputs, mel_targets,
    123             text_positions=text_positions, frame_positions=frame_positions,
--> 124             speaker_embed=speaker_embed, lengths=input_lengths)
    125 
    126         return mel_outputs, alignments, done, decoder_states

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/deepvoice3_pytorch/deepvoice3.py in forward(self, encoder_out, inputs, text_positions, frame_positions, speaker_embed, lengths)
    282             assert text_positions is not None
    283             self.start_fresh_sequence()
--> 284             outputs = self.incremental_forward(encoder_out, text_positions, speaker_embed)
    285             return outputs
    286 

~/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/deepvoice3_pytorch/deepvoice3.py in incremental_forward(self, encoder_out, text_positions, speaker_embed, initial_input, test_inputs)
    376         if self.speaker_proj1 is not None:
    377             w = w * F.sigmoid(self.speaker_proj1(speaker_embed)).view(-1)
--> 378         text_pos_embed = self.embed_keys_positions(text_positions, w)
    379         keys = keys + text_pos_embed
    380 

/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/deepvoice3_pytorch/modules.py in forward(self, x, w)
     49         if isscaler or w.size(0) == 1:
     50             weight = sinusoidal_encode(self.weight, w)
---> 51             return self._backend.Embedding.apply(
     52                 x, weight,
     53                 padding_idx, self.max_norm, self.norm_type,

/usr/local/lib/python3.6/site-packages/torch/nn/backends/backend.py in __getattr__(self, name)
      8         fn = self.function_classes.get(name)
      9         if fn is None:
---> 10             raise NotImplementedError
     11         return fn
     12 

NotImplementedError: 
```

**Comment by mrgloom** [comment]
Seems `pip install -q torch==0.3.1` under virtual env fixed the problem.

**Comment by mennatallah644** [comment]
@mrgloom  
i have the same error and i put the command in command prompt but it gave me error 
would you please tell me how did exactly you make it ?

**Comment by kapoorparul** [comment]
> Seems `pip install -q torch==0.3.1` under virtual env fixed the problem.

I am still not able to solve this issue, I get this attribute error instead -
AttributeError: 'SinusoidalEncoding' object has no attribute '_backend'
