### ISSUE TITLE
utf-8 can't decode byte 0xff

### ISSUE THREAD

**Issue by devpyhton** [r9y9/deepvoice3_pytorch#161]
Hi.
try to build a custom dataset for another language base on utf-8, everything goes well and i build a tiny dataset for multi-speaker to test 

but when i try to run preprocess.py i get an error as follow:
```bash
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/kingeng/Desktop/codes/vscode/deepvoice3_pytorch/json_meta.py", line 182, in _process_utterance
    labels = hts.load(lab_path)
  File "/home/kingeng/venvs/pytorch-gpu/lib/python3.6/site-packages/nnmnkwii/io/hts.py", line 302, in load
    return labels.load(path, lines)
  File "/home/kingeng/venvs/pytorch-gpu/lib/python3.6/site-packages/nnmnkwii/io/hts.py", line 176, in load
    lines = f.readlines()
  File "/home/kingeng/venvs/pytorch-gpu/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final, )
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 45: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 59, in <module>
    preprocess(mod, in_dir, out_dir, num_workers)
  File "preprocess.py", line 23, in preprocess
    metadata = mod.build_from_path(in_dir, out_dir, num_workers, tqdm=tqdm)
  File "/home/kingeng/Desktop/codes/vscode/deepvoice3_pytorch/json_meta.py", line 139, in build_from_path
    results = [future.result() for future in tqdm(futures)]
  File "/home/kingeng/Desktop/codes/vscode/deepvoice3_pytorch/json_meta.py", line 139, in <listcomp>
    results = [future.result() for future in tqdm(futures)]
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 45: invalid start byte
```
change everything that might cause the problem but still same error can you please take a look and help ?

**Comment by Ella77** [comment]
did you write json file with utf-8 option ? I erased json and recreated with that and it was solved for me.
