### ISSUE TITLE
Error preprocess.py

### ISSUE THREAD

**Issue by nikigre** [r9y9/deepvoice3_pytorch#167]
Hi! I installed all like it is described in when I run this command:
`sudo python3 preprocess.py --preset=presets/deepvoice3_ljspeech.json ljspeech ~/data/LJSpeech-1.0/ ./data/ljspeech`
I get this error:

```
Traceback (most recent call last):
  File "preprocess.py", line 58, in <module>
    mod = importlib.import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/d/tts2/deepvoice3_pytorch/ljspeech.py", line 5, in <module>
    import audio
  File "/mnt/d/tts2/deepvoice3_pytorch/audio.py", line 1, in <module>
    import librosa
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/core/__init__.py", line 109, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/core/audio.py", line 10, in <module>
    import scipy.signal
  File "/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/__init__.py", line 305, in <module>
    from .spectral import *
  File "/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/spectral.py", line 10, in <module>
    from ._spectral import lombscargle
ImportError: cannot import name 'lombscargle'
```

I tried `sudo pip3 install lombscargle`. But it throws this error:
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/lombscargle/
```

What am I doing wrong?

**Comment by r9y9** [comment]
Looks like the error comes from librosa.load. Could you share us the output of the `librosa.show_versions()`?

```py
In [1]: import librosa

In [2]: librosa.show_versions()
INSTALLED VERSIONS
------------------
python: 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

librosa: 0.6.2

audioread: 2.1.6
numpy: 1.16.4
scipy: 1.2.0
sklearn: 0.20.2
joblib: 0.12.4
decorator: 4.3.0
six: 1.11.0
resampy: 0.2.1

numpydoc: 0.8.0
sphinx: 1.8.0b1
sphinx_rtd_theme: 0.4.2
sphinxcontrib.versioning: None
matplotlib: 3.0.1
numba: 0.40.0
```

**Comment by nikigre** [comment]
Hi!
I get this:
```
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/core/__init__.py", line 109, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/nikigre/.local/lib/python3.6/site-packages/librosa/core/audio.py", line 10, in <module>
    import scipy.signal
  File "/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/__init__.py", line 305, in <module>
    from .spectral import *
  File "/home/nikigre/.local/lib/python3.6/site-packages/scipy/signal/spectral.py", line 10, in <module>
    from ._spectral import lombscargle
ImportError: cannot import name 'lombscargle'
>>> librosa.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'librosa' is not defined
>>>
```

**Comment by r9y9** [comment]
Apparently, you are failing to install librosa correctly. Please file an issue to https://github.com/librosa/librosa.
