### ISSUE TITLE
No module named version

### ISSUE THREAD

**Issue by mahmoodn** [r9y9/deepvoice3_pytorch#180]
Although I have installed `version`, the preprocess code give me an error that `no module name version`.

```
mn@fury0:/mnt/local/mn/deepvoice3_pytorch$ pip install --user version
Collecting version
  Downloading https://files.pythonhosted.org/packages/fd/b6/fa3b2c859d4d8817a106e4272029d78a2afbca0a27139997a4e5515bbf60/version-0.1.1.tar.gz
Building wheels for collected packages: version
  Running setup.py bdist_wheel for version ... done
  Stored in directory: /home/mn/.cache/pip/wheels/f9/92/c8/e5e619e0d562662e978c46ae88bed8698e3e108b47e393e6c3
Successfully built version
Installing collected packages: version
Successfully installed version-0.1.1
mn@fury0:/mnt/local/mn/deepvoice3_pytorch$ python preprocess.py --preset=presets/deepvoice3_ljspeech.json ljspeech ./data/LJSpeech-1.1
Traceback (most recent call last):
  File "preprocess.py", line 18, in <module>
    from hparams import hparams, hparams_debug_string
  File "/mnt/local/mn/deepvoice3_pytorch/hparams.py", line 1, in <module>
    from deepvoice3_pytorch.tfcompat.hparam import HParams
  File "/mnt/local/mn/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py", line 3, in <module>
    from .version import __version__
ImportError: No module named version
```

How can I fix that?

**Comment by r9y9** [comment]
I guess this is a dup of #125
