### ISSUE TITLE
Problem with lws package 

### ISSUE THREAD

**Issue by Parvez2017** [r9y9/deepvoice3_pytorch#218]
When I run the ljspeech.py file it gives the following error 

> TypeError: 'module' object is not callable

The full trace is the following 
`concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/user/parvej/voice-cloning/deepvoice3_pytorch/ljspeech.py", line 63, in _process_utterance
    spectrogram = audio.spectrogram(wav).astype(np.float32)
  File "/home/user/parvej/voice-cloning/deepvoice3_pytorch/audio.py", line 33, in spectrogram
    D = processor.stft(preemphasis(y)).T
  File "lws.pyx", line 441, in lws.lws.stft
  File "lws.pyx", line 87, in lws.stft
TypeError: 'module' object is not callable
"""
`

**Comment by quhb2455** [comment]
hi @Parvez2017 
i have a same error, did you figure it out?

**Comment by quhb2455** [comment]
> hi @Parvez2017
> i have a same error, did you figure it out?

i figure out this error.
i just change a version of lws.
It was  v1.2.6 and update to v1.2.7
