### ISSUE TITLE
hparams is not defined while running preprocess.py

### ISSUE THREAD

**Issue by nfrik** [r9y9/deepvoice3_pytorch#34]
Ran the following command on downloaded LJSpeech dataset:

python3 preprocess.py ljspeech ~/data/LJSpeech-1.0/ ./data/ljspeech

No preprocessed data was generated and instead got an error:

NameError: name 'hparams' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 47, in <module>
    preprocess(mod, in_dir, out_dir, num_workers)
  File "preprocess.py", line 21, in preprocess
    metadata = mod.build_from_path(in_dir, out_dir, num_workers, tqdm=tqdm)
  File "/home/coglac/Documents/deepvoice3_pytorch/ljspeech.py", line 34, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "/home/coglac/Documents/deepvoice3_pytorch/ljspeech.py", line 34, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
NameError: name 'hparams' is not defined

**Comment by r9y9** [comment]
I fixed this a few hours ago. Could you pull the latest code and try again?

**Comment by nfrik** [comment]
Thanks for quick response, preprocessing works now!
