### ISSUE TITLE
checkpoints errors

### ISSUE THREAD

**Issue by yishaicohe** [r9y9/deepvoice3_pytorch#67]
I ran a training using ljspeech,
it seems to save checkpoints only when I stop training and not for every 10000iter.
do you have any idea what is the problem?

another question. when I try to synthesis using my last checkpoint, I got the next error:

Traceback (most recent call last):
  File "synthesis.py", line 131, in <module>
    checkpoint = _load(checkpoint_path)
  File "synthesis.py", line 86, in _load
    map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 420, in _load
    result = unpickler.load()
EOFError: Ran out of input

any idea ?

Thanks

**Comment by r9y9** [comment]
I'm seeing the same error. Will look into it

**Comment by r9y9** [comment]
In my case, this is because I was trying to load an *empty* checkpoint.

**Comment by r9y9** [comment]
I'm closing this. Feel free to reopen if the problem persists.
