### ISSUE TITLE
Support for pytorch v0.4

### ISSUE THREAD

**Issue by r9y9** [r9y9/deepvoice3_pytorch#77]

**Comment by engiecat** [comment]
There seems to be an error caused by new changes.
When I trigger synthesis, the following error occurs
```
Traceback (most recent call last):
  File "synthesis.py", line 144, in <module>
    model, text, p=replace_pronunciation_prob, speaker_id=speaker_id, fast=True)
  File "synthesis.py", line 67, in tts
    sequence, text_positions=text_positions, speaker_ids=speaker_ids)
  File "H:\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\__init__.py", line 79, in forward
    text_positions, frame_positions, input_lengths)
  File "H:\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\__init__.py", line 124, in forward
    speaker_embed=speaker_embed, lengths=input_lengths)
  File "H:\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\deepvoice3.py", line 284, in forward
    outputs = self.incremental_forward(encoder_out, text_positions, speaker_embed)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\deepvoice3.py", line 420, in incremental_forward
    x = f.incremental_forward(x, speaker_embed)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\modules.py", line 143, in incremental_forward
    return self._forward(x, speaker_embed, True)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\modules.py", line 150, in _forward
    x = self.conv.incremental_forward(x)
  File "H:\Tensorflow_Study\git\dv3_torch04\deepvoice3_pytorch\conv.py", line 43, in incremental_forward
    input = torch.Tensor(self.input_buffer)
TypeError: expected torch.FloatTensor (got torch.cuda.FloatTensor)
```
For now, I had created a quick fix by changing line43 of conv.py to
`input = torch.Tensor(self.input_buffer.cpu()).cuda()` 
but I think that this will cause performance drop.

**Comment by r9y9** [comment]
Thanks for the report. I will look into it.

**Comment by r9y9** [comment]
Fixed in https://github.com/r9y9/deepvoice3_pytorch/commit/7b6f82f468cb3355dc745279d6506bf677c285ca

**Comment by r9y9** [comment]
Turn out that after fixing for pytorch v0.4, I cannot get reasonable speech quality. Not sure what is the problem yet, I should look into it closely..,

**Comment by r9y9** [comment]
For the record, 7907592c5fd5a86b47184bd977fb5b9f3037550c with deepvoice3_ljspeech preset works

**Comment by engiecat** [comment]
just confirmed that at least synthesis.py works equally between pytorch 0.3 version and current version. 
(Same checkpoint file, same text -> same output audio)

**Comment by r9y9** [comment]
Thanks for letting me know. Yes I mean training deepvoice3 doesn't work anymore.

**Comment by r9y9** [comment]
As for the issue I previously mentioned was actually a problem of `eval_model` in train.py. There's no issue for synthesis as you said. Fixed by https://github.com/r9y9/deepvoice3_pytorch/pull/82/commits/ec4cf2ae3c2a3e9289b3958ff28d5412710f85ca, not sure what's actually the problem is. It's hard to debug so for now I changed the args of `tts` function as same as synthesis.py; i.e., `fast=True`.
