### ISSUE TITLE
preprocess: TypeError: unorderable types: NoneType() > int()

### ISSUE THREAD

**Issue by StephenZengCn** [r9y9/deepvoice3_pytorch#8]
```
python3 preprocess.py ljspeech ./data/LJSpeech-1.0/ ./data/ljspeech
  0%|                                                                                   | 0/13100 [00:00<?, ?it/s]concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/data1/demobin/deepvoice3_pytorch/ljspeech.py", line 57, in _process_utterance
    spectrogram = audio.spectrogram(wav).astype(np.float32)
  File "/data1/demobin/deepvoice3_pytorch/audio.py", line 32, in spectrogram
    D = _lws_processor().stft(preemphasis(y)).T
  File "/data1/demobin/deepvoice3_pytorch/audio.py", line 53, in _lws_processor
    return lws.lws(hparams.fft_size, hparams.hop_size, mode="speech")
  File "lws.pyx", line 357, in lws.lws.__init__ (lws.bycython.cpp:15047)
TypeError: unorderable types: NoneType() > int()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 55, in <module>
    preprocess_ljspeech(in_dir, out_dir, num_workers)
  File "preprocess.py", line 21, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir, num_workers, tqdm=tqdm)
  File "/data1/demobin/deepvoice3_pytorch/ljspeech.py", line 34, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "/data1/demobin/deepvoice3_pytorch/ljspeech.py", line 34, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: unorderable types: NoneType() > int()
```

**Comment by r9y9** [comment]
It seems `hparams.fft_size` or `hparams.hop_size` is None. Can you check that what values set for these parameters?

**Comment by StephenZengCn** [comment]
default hparams.py
```
    # Audio:
    num_mels=80,
    fft_size=1024,
    hop_size=256,
    sample_rate=22050,
    preemphasis=0.97,
    min_level_db=-100,
    ref_level_db=20,

```

**Comment by r9y9** [comment]
Can you insert `print` into the `audio.py` and check the values? I'm wondering you have multiple `hparams.py` in your package paths and loading a different `hparams.py`.

**Comment by StephenZengCn** [comment]
```
...
def _lws_processor():
    print(hparams.fft_size, hparams.hop_size)
    return lws.lws(hparams.fft_size, hparams.hop_size, mode="speech")
...
```

```
...
1024 256
1024 256
1024 256
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/data1/demobin/deepvoice3_pytorch/ljspeech.py", line 57, in _process_utterance
    spectrogram = audio.spectrogram(wav).astype(np.float32)
  File "/data1/demobin/deepvoice3_pytorch/audio.py", line 32, in spectrogram
    D = _lws_processor().stft(preemphasis(y)).T
  File "/data1/demobin/deepvoice3_pytorch/audio.py", line 54, in _lws_processor
    return lws.lws(hparams.fft_size, hparams.hop_size, mode="speech")
  File "lws.pyx", line 357, in lws.lws.__init__ (lws.bycython.cpp:15047)
TypeError: unorderable types: NoneType() > int()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 55, in <module>
    preprocess_ljspeech(in_dir, out_dir, num_workers)
  File "preprocess.py", line 21, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir, num_workers, tqdm=tqdm)
  File "/data1/demobin/deepvoice3_pytorch/ljspeech.py", line 34, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "/data1/demobin/deepvoice3_pytorch/ljspeech.py", line 34, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: unorderable types: NoneType() > int()
1024 256
1024 256
...
```

**Comment by StephenZengCn** [comment]
any suggestion?

**Comment by StephenZengCn** [comment]
it's the main repo, i havn't modify anything yet.

**Comment by StephenZengCn** [comment]
by debug with num_workers=1, i locate the wav produce the exception
```
data/LJSpeech-1.0/wavs/LJ001-0046.wav
```

**Comment by r9y9** [comment]
Can you check if `pip install "lws==1.0"` works?

**Comment by r9y9** [comment]
Seems there's a new release v1.1, which I haven't tried it yet.

**Comment by StephenZengCn** [comment]
bingo! thx!
