### ISSUE TITLE
Unable to synthesize from checkpoint

### ISSUE THREAD

**Issue by vignesh-almond** [r9y9/deepvoice3_pytorch#87]
I created a virtual env in conda with python 3.5, then installed the prerequisites and then cloned the master branch, did a pip install -e "[train]", then did a git checkout to the specified commit and ran the following command 

python synthesis.py --hparams="builder=deepvoice3,preset=deepvoice3_ljspeech" /root/sharedfolder/repo/deepvoice3/checkpoints/20171213_deepvoice3_checkpoint_step000210000.pth /root/sharedfolder/repo/deepvoice3/text_list.txt /root/sharedfolder/repo/deepvoice3/output/

but I am getting the following error 

```
Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': 'builder=deepvoice3,preset=deepvoice3_ljspeech',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': '/root/sharedfolder/repo/deepvoice3/checkpoints/20171213_deepvoice3_checkpoint_step000210000.pth',
 '<dst_dir>': '/root/sharedfolder/repo/deepvoice3/output/',
 '<text_list_file>': '/root/sharedfolder/repo/deepvoice3/text_list.txt'}
Traceback (most recent call last):
  File "synthesis.py", line 97, in <module>
    hparams.parse(args["--hparams"])
  File "/root/anaconda2/envs/deep_torch/lib/python3.5/site-packages/tensorflow/contrib/training/python/training/hparam.py", line 326, in parse
    values_map = parse_values(values, type_map)
  File "/root/anaconda2/envs/deep_torch/lib/python3.5/site-packages/tensorflow/contrib/training/python/training/hparam.py", line 86, in parse_values
    raise ValueError('Unknown hyperparameter type for %s' % name)
ValueError: Unknown hyperparameter type for preset
```
Without the hparams options I am getting the following error 
```
Traceback (most recent call last):
  File "synthesis.py", line 125, in <module>
    model.load_state_dict(checkpoint["state_dict"])
  File "/root/anaconda2/envs/deep_torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiSpeakerTTSModel:
	Missing key(s) in state_dict: "seq2seq.encoder.convnet.0.weight_v", "seq2seq.encoder.convnet.0.weight_g", "seq2seq.encoder.convnet.0.bias", "seq2seq.encoder.convnet.2.weight_v", "seq2seq.encoder.convnet.2.weight_g", "seq2seq.encoder.convnet.2.bias", "seq2seq.encoder.convnet.3.conv.weight_v", "seq2seq.encoder.convnet.3.conv.weight_g", "seq2seq.encoder.convnet.3.conv.bias", "seq2seq.encoder.convnet.4.conv.weight_v", "seq2seq.encoder.convnet.4.conv.weight_g", "seq2seq.encoder.convnet.4.conv.bias", "seq2seq.encoder.convnet.5.conv.weight_v", "seq2seq.encoder.convnet.5.conv.weight_g", "seq2seq.encoder.convnet.5.conv.bias", "seq2seq.encoder.convnet.6.conv.weight_v", "seq2seq.encoder.convnet.6.conv.weight_g", "seq2seq.encoder.convnet.6.conv.bias", "seq2seq.encoder.convnet.7.conv.weight_v", "seq2seq.encoder.convnet.7.conv.weight_g", "seq2seq.encoder.convnet.7.conv.bias", "seq2seq.encoder.convnet.8.conv.weight_v", "seq2seq.encoder.convnet.8.conv.weight_g", "seq2seq.encoder.convnet.8.conv.bias", "seq2seq.encoder.convnet.9.conv.weight_v", "seq2seq.encoder.convnet.9.conv.weight_g", "seq2seq.encoder.convnet.9.conv.bias", "seq2seq.encoder.convnet.10.conv.weight_v", "seq2seq.encoder.convnet.10.conv.weight_g", "seq2seq.encoder.convnet.10.conv.bias", "seq2seq.encoder.convnet.11.conv.weight_v", "seq2seq.encoder.convnet.11.conv.weight_g", "seq2seq.encoder.convnet.11.conv.bias", "seq2seq.encoder.convnet.12.conv.weight_v", "seq2seq.encoder.convnet.12.conv.weight_g", "seq2seq.encoder.convnet.12.conv.bias", "seq2seq.encoder.convnet.13.conv.weight_v", "seq2seq.encoder.convnet.13.conv.weight_g", "seq2seq.encoder.convnet.13.conv.bias", "seq2seq.decoder.audio_encoder_modules.0.weight_v", "seq2seq.decoder.audio_encoder_modules.0.weight_g", "seq2seq.decoder.audio_encoder_modules.0.bias", "seq2seq.decoder.audio_encoder_modules.2.weight_v", "seq2seq.decoder.audio_encoder_modules.2.weight_g", "seq2seq.decoder.audio_encoder_modules.2.bias", "seq2seq.decoder.audio_encoder_modules.4.weight_v", "seq2seq.decoder.audio_encoder_modules.4.weight_g", "seq2seq.decoder.audio_encoder_modules.4.bias", "seq2seq.decoder.audio_encoder_modules.5.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.5.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.5.conv.bias", "seq2seq.decoder.audio_encoder_modules.6.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.6.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.6.conv.bias", "seq2seq.decoder.audio_encoder_modules.7.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.7.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.7.conv.bias", "seq2seq.decoder.audio_encoder_modules.8.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.8.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.8.conv.bias", "seq2seq.decoder.audio_encoder_modules.9.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.9.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.9.conv.bias", "seq2seq.decoder.audio_encoder_modules.10.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.10.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.10.conv.bias", "seq2seq.decoder.audio_encoder_modules.11.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.11.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.11.conv.bias", "seq2seq.decoder.audio_encoder_modules.12.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.12.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.12.conv.bias", "seq2seq.decoder.audio_encoder_modules.13.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.13.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.13.conv.bias", "seq2seq.decoder.audio_encoder_modules.14.conv.weight_v", "seq2seq.decoder.audio_encoder_modules.14.conv.weight_g", "seq2seq.decoder.audio_encoder_modules.14.conv.bias", "seq2seq.decoder.attention.query_projection.weight_v", "seq2seq.decoder.attention.query_projection.weight_g", "seq2seq.decoder.attention.query_projection.bias", "seq2seq.decoder.attention.key_projection.weight_v", "seq2seq.decoder.attention.key_projection.weight_g", "seq2seq.decoder.attention.key_projection.bias", "seq2seq.decoder.attention.value_projection.weight_v", "seq2seq.decoder.attention.value_projection.weight_g", "seq2seq.decoder.attention.value_projection.bias", "seq2seq.decoder.attention.out_projection.weight_v", "seq2seq.decoder.attention.out_projection.weight_g", "seq2seq.decoder.attention.out_projection.bias", "seq2seq.decoder.audio_decoder_modules.0.weight_v", "seq2seq.decoder.audio_decoder_modules.0.weight_g", "seq2seq.decoder.audio_decoder_modules.0.bias", "seq2seq.decoder.audio_decoder_modules.1.conv.weight_v", "seq2seq.decoder.audio_decoder_modules.1.conv.weight_g", "seq2seq.decoder.audio_decoder_modules.1.conv.bias", "seq2seq.decoder.audio_decoder_modules.2.conv.weight_v", "seq2seq.decoder.audio_decoder_modules.2.conv.weight_g", "seq2seq.decoder.audio_decoder_modules.2.conv.bias", "seq2seq.decoder.audio_decoder_modules.3.conv.weight_v", "seq2seq.decoder.audio_decoder_modules.3.conv.weight_g", "seq2seq.decoder.audio_decoder_modules.3.conv.bias", "seq2seq.decoder.audio_decoder_modules.4.conv.weight_v", "seq2seq.decoder.audio_decoder_modules.4.conv.weight_g", "seq2seq.decoder.audio_decoder_modules.4.conv.bias", "seq2seq.decoder.audio_decoder_modules.5.conv.weight_v", "seq2seq.decoder.audio_decoder_modules.5.conv.weight_g", "seq2seq.decoder.audio_decoder_modules.5.conv.bias", "seq2seq.decoder.audio_decoder_modules.6.conv.weight_v", "seq2seq.decoder.audio_decoder_modules.6.conv.weight_g", "seq2seq.decoder.audio_decoder_modules.6.conv.bias", "seq2seq.decoder.audio_decoder_modules.7.weight_v", "seq2seq.decoder.audio_decoder_modules.7.weight_g", "seq2seq.decoder.audio_decoder_modules.7.bias", "seq2seq.decoder.audio_decoder_modules.9.weight_v", "seq2seq.decoder.audio_decoder_modules.9.weight_g", "seq2seq.decoder.audio_decoder_modules.9.bias", "seq2seq.decoder.audio_decoder_modules.11.weight_v", "seq2seq.decoder.audio_decoder_modules.11.weight_g", "seq2seq.decoder.audio_decoder_modules.11.bias", "postnet.convnet.0.weight_v", "postnet.convnet.0.weight_g", "postnet.convnet.0.bias", "postnet.convnet.1.conv.weight_v", "postnet.convnet.1.conv.weight_g", "postnet.convnet.1.conv.bias", "postnet.convnet.2.conv.weight_v", "postnet.convnet.2.conv.weight_g", "postnet.convnet.2.conv.bias", "postnet.convnet.3.weight_v", "postnet.convnet.3.weight_g", "postnet.convnet.3.bias", "postnet.convnet.4.conv.weight_v", "postnet.convnet.4.conv.weight_g", "postnet.convnet.4.conv.bias", "postnet.convnet.5.conv.weight_v", "postnet.convnet.5.conv.weight_g", "postnet.convnet.5.conv.bias", "postnet.convnet.6.weight_v", "postnet.convnet.6.weight_g", "postnet.convnet.6.bias", "postnet.convnet.7.conv.weight_v", "postnet.convnet.7.conv.weight_g", "postnet.convnet.7.conv.bias", "postnet.convnet.8.conv.weight_v", "postnet.convnet.8.conv.weight_g", "postnet.convnet.8.conv.bias", "postnet.convnet.9.weight_v", "postnet.convnet.9.weight_g", "postnet.convnet.9.bias", "postnet.convnet.10.conv.weight_v", "postnet.convnet.10.conv.weight_g", "postnet.convnet.10.conv.bias", "postnet.convnet.11.conv.weight_v", "postnet.convnet.11.conv.weight_g", "postnet.convnet.11.conv.bias", "postnet.convnet.12.weight_v", "postnet.convnet.12.weight_g", "postnet.convnet.12.bias", "postnet.convnet.13.weight_v", "postnet.convnet.13.weight_g", "postnet.convnet.13.bias", "postnet.convnet.15.weight_v", "postnet.convnet.15.weight_g", "postnet.convnet.15.bias", "postnet.convnet.17.weight_v", "postnet.convnet.17.weight_g", "postnet.convnet.17.bias". 
	Unexpected key(s) in state_dict: "seq2seq.encoder.convolutions.0.bias", "seq2seq.encoder.convolutions.0.weight_g", "seq2seq.encoder.convolutions.0.weight_v", "seq2seq.encoder.convolutions.2.conv.bias", "seq2seq.encoder.convolutions.2.conv.weight_g", "seq2seq.encoder.convolutions.2.conv.weight_v", "seq2seq.encoder.convolutions.3.conv.bias", "seq2seq.encoder.convolutions.3.conv.weight_g", "seq2seq.encoder.convolutions.3.conv.weight_v", "seq2seq.encoder.convolutions.4.conv.bias", "seq2seq.encoder.convolutions.4.conv.weight_g", "seq2seq.encoder.convolutions.4.conv.weight_v", "seq2seq.encoder.convolutions.5.conv.bias", "seq2seq.encoder.convolutions.5.conv.weight_g", "seq2seq.encoder.convolutions.5.conv.weight_v", "seq2seq.encoder.convolutions.6.conv.bias", "seq2seq.encoder.convolutions.6.conv.weight_g", "seq2seq.encoder.convolutions.6.conv.weight_v", "seq2seq.encoder.convolutions.7.conv.bias", "seq2seq.encoder.convolutions.7.conv.weight_g", "seq2seq.encoder.convolutions.7.conv.weight_v", "seq2seq.encoder.convolutions.8.conv.bias", "seq2seq.encoder.convolutions.8.conv.weight_g", "seq2seq.encoder.convolutions.8.conv.weight_v", "seq2seq.encoder.convolutions.9.conv.bias", "seq2seq.encoder.convolutions.9.conv.weight_g", "seq2seq.encoder.convolutions.9.conv.weight_v", "seq2seq.encoder.convolutions.10.conv.bias", "seq2seq.encoder.convolutions.10.conv.weight_g", "seq2seq.encoder.convolutions.10.conv.weight_v", "seq2seq.encoder.convolutions.11.conv.bias", "seq2seq.encoder.convolutions.11.conv.weight_g", "seq2seq.encoder.convolutions.11.conv.weight_v", "seq2seq.encoder.convolutions.12.bias", "seq2seq.encoder.convolutions.12.weight_g", "seq2seq.encoder.convolutions.12.weight_v", "seq2seq.decoder.preattention.0.bias", "seq2seq.decoder.preattention.0.weight_g", "seq2seq.decoder.preattention.0.weight_v", "seq2seq.decoder.preattention.2.conv.bias", "seq2seq.decoder.preattention.2.conv.weight_g", "seq2seq.decoder.preattention.2.conv.weight_v", "seq2seq.decoder.preattention.3.conv.bias", "seq2seq.decoder.preattention.3.conv.weight_g", "seq2seq.decoder.preattention.3.conv.weight_v", "seq2seq.decoder.convolutions.0.conv.bias", "seq2seq.decoder.convolutions.0.conv.weight_g", "seq2seq.decoder.convolutions.0.conv.weight_v", "seq2seq.decoder.convolutions.1.conv.bias", "seq2seq.decoder.convolutions.1.conv.weight_g", "seq2seq.decoder.convolutions.1.conv.weight_v", "seq2seq.decoder.convolutions.2.conv.bias", "seq2seq.decoder.convolutions.2.conv.weight_g", "seq2seq.decoder.convolutions.2.conv.weight_v", "seq2seq.decoder.convolutions.3.conv.bias", "seq2seq.decoder.convolutions.3.conv.weight_g", "seq2seq.decoder.convolutions.3.conv.weight_v", "seq2seq.decoder.convolutions.4.conv.bias", "seq2seq.decoder.convolutions.4.conv.weight_g", "seq2seq.decoder.convolutions.4.conv.weight_v", "seq2seq.decoder.attention.0.query_projection.bias", "seq2seq.decoder.attention.0.query_projection.weight_g", "seq2seq.decoder.attention.0.query_projection.weight_v", "seq2seq.decoder.attention.0.key_projection.bias", "seq2seq.decoder.attention.0.key_projection.weight_g", "seq2seq.decoder.attention.0.key_projection.weight_v", "seq2seq.decoder.attention.0.value_projection.bias", "seq2seq.decoder.attention.0.value_projection.weight_g", "seq2seq.decoder.attention.0.value_projection.weight_v", "seq2seq.decoder.attention.0.out_projection.bias", "seq2seq.decoder.attention.0.out_projection.weight_g", "seq2seq.decoder.attention.0.out_projection.weight_v", "seq2seq.decoder.attention.4.query_projection.bias", "seq2seq.decoder.attention.4.query_projection.weight_g", "seq2seq.decoder.attention.4.query_projection.weight_v", "seq2seq.decoder.attention.4.key_projection.bias", "seq2seq.decoder.attention.4.key_projection.weight_g", "seq2seq.decoder.attention.4.key_projection.weight_v", "seq2seq.decoder.attention.4.value_projection.bias", "seq2seq.decoder.attention.4.value_projection.weight_g", "seq2seq.decoder.attention.4.value_projection.weight_v", "seq2seq.decoder.attention.4.out_projection.bias", "seq2seq.decoder.attention.4.out_projection.weight_g", "seq2seq.decoder.attention.4.out_projection.weight_v", "postnet.convolutions.0.bias", "postnet.convolutions.0.weight_g", "postnet.convolutions.0.weight_v", "postnet.convolutions.1.bias", "postnet.convolutions.1.weight_g", "postnet.convolutions.1.weight_v", "postnet.convolutions.2.conv.bias", "postnet.convolutions.2.conv.weight_g", "postnet.convolutions.2.conv.weight_v", "postnet.convolutions.3.conv.bias", "postnet.convolutions.3.conv.weight_g", "postnet.convolutions.3.conv.weight_v", "postnet.convolutions.4.bias", "postnet.convolutions.4.weight_g", "postnet.convolutions.4.weight_v", "postnet.convolutions.5.conv.bias", "postnet.convolutions.5.conv.weight_g", "postnet.convolutions.5.conv.weight_v", "postnet.convolutions.6.conv.bias", "postnet.convolutions.6.conv.weight_g", "postnet.convolutions.6.conv.weight_v", "postnet.convolutions.7.conv.bias", "postnet.convolutions.7.conv.weight_g", "postnet.convolutions.7.conv.weight_v", "postnet.convolutions.8.conv.bias", "postnet.convolutions.8.conv.weight_g", "postnet.convolutions.8.conv.weight_v", "postnet.convolutions.9.bias", "postnet.convolutions.9.weight_g", "postnet.convolutions.9.weight_v", "postnet.convolutions.11.conv.bias", "postnet.convolutions.11.conv.weight_g", "postnet.convolutions.11.conv.weight_v", "postnet.convolutions.12.conv.bias", "postnet.convolutions.12.conv.weight_g", "postnet.convolutions.12.conv.weight_v", "postnet.convolutions.13.bias", "postnet.convolutions.13.weight_g", "postnet.convolutions.13.weight_v". 
	While copying the parameter named "seq2seq.encoder.embed_tokens.weight", whose dimensions in the model are torch.Size([149, 128]) and whose dimensions in the checkpoint are torch.Size([149, 256]).
```
Am I doing something wrong here with the synthesis option ?

**Comment by r9y9** [comment]
Sorry but the old code doesn't accept `preset` parameter. See README of the specific git commit: https://github.com/r9y9/deepvoice3_pytorch/tree/43579764f35de6b8bac2b18b52a06e4e11b705b2. Or you could try more recent checkpoint https://www.dropbox.com/s/5ucl9remrwy5oeg/20180505_deepvoice3_checkpoint_step000640000.pth?dl=0 that works on master.

**Comment by r9y9** [comment]
I'll update README soon
